### ISSUE TITLE
Opencv not working with phthon version 3.7

### ISSUE THREAD

**Issue by abbk1** [abbk1/hello_world#1]
Below is the error code im receiving when running the program please help!

C:\Users\ABUBAKAR-PC\Desktop\Face_Recognition_Attendance_System-master\venv\Scripts\python.exe C:/Users/ABUBAKAR-PC/Desktop/Face_Recognition_Attendance_System-master/firstpage_gui.py
Traceback (most recent call last):
  File "training_dataset.py", line 5, in <module>
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2' has no attribute 'face'
